apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: crowdauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: us-central1-docker.pkg.dev/projet-mana/demo-repo/auth-service
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/crowdauth"
            - name: JWT_SECRET
              value: "supersecret"
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
